/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as OrderResultIndexRouteImport } from './routes/order/result/index'
import { Route as DocumentsUserAgreementIndexRouteImport } from './routes/documents/user-agreement/index'
import { Route as DocumentsPrivacyPolicyIndexRouteImport } from './routes/documents/privacy-policy/index'
import { Route as DocumentsAdvertisingMessagesIndexRouteImport } from './routes/documents/advertising-messages/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderResultIndexRoute = OrderResultIndexRouteImport.update({
  id: '/order/result/',
  path: '/order/result/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsUserAgreementIndexRoute =
  DocumentsUserAgreementIndexRouteImport.update({
    id: '/documents/user-agreement/',
    path: '/documents/user-agreement/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsPrivacyPolicyIndexRoute =
  DocumentsPrivacyPolicyIndexRouteImport.update({
    id: '/documents/privacy-policy/',
    path: '/documents/privacy-policy/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsAdvertisingMessagesIndexRoute =
  DocumentsAdvertisingMessagesIndexRouteImport.update({
    id: '/documents/advertising-messages/',
    path: '/documents/advertising-messages/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/product/$slug': typeof ProductSlugRoute
  '/cart': typeof CartIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/documents/advertising-messages': typeof DocumentsAdvertisingMessagesIndexRoute
  '/documents/privacy-policy': typeof DocumentsPrivacyPolicyIndexRoute
  '/documents/user-agreement': typeof DocumentsUserAgreementIndexRoute
  '/order/result': typeof OrderResultIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product/$slug': typeof ProductSlugRoute
  '/cart': typeof CartIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/documents/advertising-messages': typeof DocumentsAdvertisingMessagesIndexRoute
  '/documents/privacy-policy': typeof DocumentsPrivacyPolicyIndexRoute
  '/documents/user-agreement': typeof DocumentsUserAgreementIndexRoute
  '/order/result': typeof OrderResultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/product/$slug': typeof ProductSlugRoute
  '/cart/': typeof CartIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/documents/advertising-messages/': typeof DocumentsAdvertisingMessagesIndexRoute
  '/documents/privacy-policy/': typeof DocumentsPrivacyPolicyIndexRoute
  '/documents/user-agreement/': typeof DocumentsUserAgreementIndexRoute
  '/order/result/': typeof OrderResultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/product/$slug'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/documents/advertising-messages'
    | '/documents/privacy-policy'
    | '/documents/user-agreement'
    | '/order/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/product/$slug'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/documents/advertising-messages'
    | '/documents/privacy-policy'
    | '/documents/user-agreement'
    | '/order/result'
  id:
    | '__root__'
    | '/'
    | '/product/$slug'
    | '/cart/'
    | '/checkout/'
    | '/orders/'
    | '/documents/advertising-messages/'
    | '/documents/privacy-policy/'
    | '/documents/user-agreement/'
    | '/order/result/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductSlugRoute: typeof ProductSlugRoute
  CartIndexRoute: typeof CartIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  DocumentsAdvertisingMessagesIndexRoute: typeof DocumentsAdvertisingMessagesIndexRoute
  DocumentsPrivacyPolicyIndexRoute: typeof DocumentsPrivacyPolicyIndexRoute
  DocumentsUserAgreementIndexRoute: typeof DocumentsUserAgreementIndexRoute
  OrderResultIndexRoute: typeof OrderResultIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/result/': {
      id: '/order/result/'
      path: '/order/result'
      fullPath: '/order/result/'
      preLoaderRoute: typeof OrderResultIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/user-agreement/': {
      id: '/documents/user-agreement/'
      path: '/documents/user-agreement'
      fullPath: '/documents/user-agreement/'
      preLoaderRoute: typeof DocumentsUserAgreementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/privacy-policy/': {
      id: '/documents/privacy-policy/'
      path: '/documents/privacy-policy'
      fullPath: '/documents/privacy-policy/'
      preLoaderRoute: typeof DocumentsPrivacyPolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/advertising-messages/': {
      id: '/documents/advertising-messages/'
      path: '/documents/advertising-messages'
      fullPath: '/documents/advertising-messages/'
      preLoaderRoute: typeof DocumentsAdvertisingMessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductSlugRoute: ProductSlugRoute,
  CartIndexRoute: CartIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  DocumentsAdvertisingMessagesIndexRoute:
    DocumentsAdvertisingMessagesIndexRoute,
  DocumentsPrivacyPolicyIndexRoute: DocumentsPrivacyPolicyIndexRoute,
  DocumentsUserAgreementIndexRoute: DocumentsUserAgreementIndexRoute,
  OrderResultIndexRoute: OrderResultIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
